version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10
    working_directory: /tmp

commands:
  install_deps:
    steps:
      - restore_cache:
          path: /tmp/code
          keys:
            - v2-yarn-sha-{{ checksum "yarn.lock" }}
            - v2-yarn-sha-
      - run:
          name: Install js dependencies
          command: yarn
          path: /tmp/code
      - save_cache:
          key: v2-yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - /tmp/code/node_modules

jobs:
  install:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - checkout:
          path: /tmp/code
      - install_deps
      - persist_to_workspace:
          root: /tmp/code
          paths:
            - node_modules
            - packages
  lint:
    executor: my-executor
    steps:
      - checkout:
          path: /tmp/code
      - attach_workspace:
          at: /tmp/code
      - run: ls code/packages/frontend
      - run: cd code/ && yarn lint

  test:
    executor: my-executor
    steps:
      - checkout:
          path: /tmp/code
      - attach_workspace:
          at: /tmp/code
      - run: ls code/packages/frontend
      - run: cd code/ && yarn test

workflows:
  workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
