version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10
    working_directory: /tmp

commands:
  install_deps:
    steps:
      - run:
          name: View install environment
          command: |
            node --version
            yarn --version
      - restore_cache:
          keys:
            - v2-yarn-sha-{{ checksum "yarn.lock" }}
            - v2-yarn-sha-
      - run:
          name: Install js dependencies
          command: yarn

jobs:
  install:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - checkout:
          path: /tmp/workspace
      - install_deps
      - run: echo install
      - run: name
      - persist_to_workspace:
          root: workspace
          paths:
            - node_modules
  lint:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /myspace/workspace
      - run: echo lint
      - run: ls -la
  test:
    executor: my-executor
    steps:
      - run: echo test

workflows:
  workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
